imports:
  - { resource: services/*.php }
  - { resource: services/*.yml }

framework:
  # We currently do not depend on this setting, yet it has to be present.
  secret: opencfp
  form: ~
  csrf_protection: ~
  session:
    handler_id: session.handler.native_file
  router:
    resource: '%kernel.project_dir%/resources/config/routing.yml'

wouterj_eloquent:
  driver:   mysql
  host:     '%env(DATABASE_HOST)%'
  database: '%env(DATABASE_DATABASE)%'
  username: '%env(DATABASE_USER)%'
  password: '%env(DATABASE_PASSWORD)%'
  charset:   utf8mb4
  collation: utf8mb4_unicode_ci
  prefix:    ~
  eloquent: true

twig:
  default_path: '%kernel.project_dir%/resources/views'
  debug: '%kernel.debug%'
  base_template_class: 'OpenCFP\Infrastructure\Templating\Template'
  globals:
    site:       '%config.application%'
    talkHelper: '@OpenCFP\Http\View\TalkHelper'

monolog:
  handlers:
    opencfp:
      type: stream
      path: '%kernel.logs_dir%/app.log'
      level: '%log.level%'

swiftmailer:
  host:       '%env(MAILER_HOST)%'
  port:       '%env(MAILER_PORT)%'
  username:   '%env(MAILER_USERNAME)%'
  password:   '%env(MAILER_PASSWORD)%'
  encryption: '%env(MAILER_ENCRYPTION)%'
  auth_mode:  '%env(MAILER_AUTH_MODE)%'
