services:
  _defaults:
    public: false
    autowire: true

  OpenCFP\Http\Controller\:
    resource: '%kernel.project_dir%/classes/Http/Controller/*'
    public: true
    bind:
      $applicationAirport: '%application.airport%'
      $applicationArrival: '%application.arrival%'
      $applicationDeparture: '%application.departure%'

  OpenCFP\Http\Action\:
    resource: '%kernel.project_dir%/classes/Http/Action/*'
    public: true
    bind:
      $applicationEmail: '%application.email%'
      $applicationEndDate: '%application.enddate%'
      $applicationTitle: '%application.title%'
      $authorizeUrl: '%opencfp.authorizeUrl%'
      $clientId: '%opencfp.clientId%'
      $clientSecret: '%opencfp.clientSecret%'
      $forgotForm: '@OpenCFP\Http\Form\ForgotForm'
      $redirectUri: '%opencfp.redirectUri%'
      $resetForm: '@OpenCFP\Http\Form\ResetForm'
      $resourceUri: '%opencfp.resourceUri%'
      $reviewerUsers: '%reviewer.users%'
      $showSubmissionCount: '%application.show_submission_count%'
      $tokenUrl: '%opencfp.tokenUrl%'

  OpenCFP\Http\Form\ForgotForm:
    class: Symfony\Component\Form\FormInterface
    factory: [OpenCFP\Http\Form\FormFactory, create]
    bind:
      $formType: OpenCFP\Http\Form\ForgotFormType

  OpenCFP\Http\Form\ResetForm:
    class: Symfony\Component\Form\FormInterface
    factory: [OpenCFP\Http\Form\FormFactory, create]
    bind:
      $formType: OpenCFP\Http\Form\ResetFormType

  OpenCFP\Http\View\TalkHelper:
    arguments:
      - '%talk.categories%'
      - '%talk.levels%'
      - '%talk.types%'

  OpenCFP\PathInterface:
    class: OpenCFP\Path
    bind:
      $path: '%kernel.project_dir%'

  OpenCFP\WebPath:
      class: OpenCFP\WebPath

  OpenCFP\Application\Speakers: ~

  OpenCFP\Environment:
    autowire: false
    factory: [OpenCFP\Environment, fromString]
    arguments: ['%kernel.environment%']
